// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: searchJava/searchJava.proto

package searchJava

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SearchText) Reset() {
	*x = SearchText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searchJava_searchJava_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchText) ProtoMessage() {}

func (x *SearchText) ProtoReflect() protoreflect.Message {
	mi := &file_searchJava_searchJava_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchText.ProtoReflect.Descriptor instead.
func (*SearchText) Descriptor() ([]byte, []int) {
	return file_searchJava_searchJava_proto_rawDescGZIP(), []int{0}
}

func (x *SearchText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Fullname string `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searchJava_searchJava_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_searchJava_searchJava_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_searchJava_searchJava_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SearchResult) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchResult) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

var File_searchJava_searchJava_proto protoreflect.FileDescriptor

var file_searchJava_searchJava_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x61, 0x76, 0x61, 0x2f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x4a, 0x61, 0x76, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x61, 0x76, 0x61, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x5a, 0x0a, 0x0c, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x50, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x4a, 0x61, 0x76, 0x61, 0x12, 0x42, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50,
	0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x61,
	0x76, 0x61, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x18, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x61, 0x76, 0x61, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x75, 0x72, 0x62, 0x61, 0x6e, 0x6f, 0x77,
	0x47, 0x61, 0x64, 0x61, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x3b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x61, 0x76, 0x61, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_searchJava_searchJava_proto_rawDescOnce sync.Once
	file_searchJava_searchJava_proto_rawDescData = file_searchJava_searchJava_proto_rawDesc
)

func file_searchJava_searchJava_proto_rawDescGZIP() []byte {
	file_searchJava_searchJava_proto_rawDescOnce.Do(func() {
		file_searchJava_searchJava_proto_rawDescData = protoimpl.X.CompressGZIP(file_searchJava_searchJava_proto_rawDescData)
	})
	return file_searchJava_searchJava_proto_rawDescData
}

var file_searchJava_searchJava_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_searchJava_searchJava_proto_goTypes = []interface{}{
	(*SearchText)(nil),   // 0: searchJava.SearchText
	(*SearchResult)(nil), // 1: searchJava.SearchResult
}
var file_searchJava_searchJava_proto_depIdxs = []int32{
	0, // 0: searchJava.SearchJava.SearchPeople:input_type -> searchJava.SearchText
	1, // 1: searchJava.SearchJava.SearchPeople:output_type -> searchJava.SearchResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_searchJava_searchJava_proto_init() }
func file_searchJava_searchJava_proto_init() {
	if File_searchJava_searchJava_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_searchJava_searchJava_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_searchJava_searchJava_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_searchJava_searchJava_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_searchJava_searchJava_proto_goTypes,
		DependencyIndexes: file_searchJava_searchJava_proto_depIdxs,
		MessageInfos:      file_searchJava_searchJava_proto_msgTypes,
	}.Build()
	File_searchJava_searchJava_proto = out.File
	file_searchJava_searchJava_proto_rawDesc = nil
	file_searchJava_searchJava_proto_goTypes = nil
	file_searchJava_searchJava_proto_depIdxs = nil
}
